version: "3.3"

services:
  download-service:
    build:
      context: ./
      dockerfile: Dockerfile.test
    command: ["go", "test", "-component", "-coverpkg=./..."]
    ports:
      - "23600:23600"
    environment:
      BIND_ADDR: ':23600'
      AWS_REGION: 'eu-west-2' # http://localstack:4572
      BUCKET_NAME: 'testing'
      GRACEFUL_SHUTDOWN_TIMEOUT: '5s'
      HEALTHCHECK_INTERVAL: '5s'
      HEALTHCHECK_CRITICAL_TIMEOUT: '5s'

  localstack:
    image: localstack/localstack:2.2.0
    ports:
      - "4566:4583"
    environment:
      - SERVICES=s3
      - DEBUG=0
      - AWS_DEFAULT_REGION=eu-west-2
      - EDGE_PORT=4566
    volumes:
      - ./aws:/etc/localstack/init/ready.d/
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
            