FROM golang:1.21.3-bullseye AS base

ENV GOCACHE=/go/.go/cache GOPATH=/go/.go/path TZ=Europe/London

RUN GOBIN=/bin go get github.com/cespare/reflex

# Map between the working directories of dev and live
RUN ln -s /go /dp-download-service
WORKDIR /dp-download-service