FROM golang:1.24 AS base

ENV GOCACHE=/go/.go/cache GOPATH=/go/.go/path TZ=Europe/London

RUN git config --global --add safe.directory /go

RUN GOBIN=/bin go install github.com/cespare/reflex@v0.3.1

# Map between the working directories of dev and live
RUN ln -s /go /dp-download-service
WORKDIR /dp-download-service