version: "3.3"

services:
  download-service:
    build:
      context: ./
      dockerfile: Dockerfile.test
    ports:
      - "23600:23600"
    environment:
      BIND_ADDR: 'localhost:23600'
      AWS_REGION: 'eu-west-2' # http://localstack:4572
      BUCKET_NAME: 'testing'
      GRACEFUL_SHUTDOWN_TIMEOUT: '5s'
      HEALTHCHECK_INTERVAL: '5s'
      HEALTHCHECK_CRITICAL_TIMEOUT: '5s'
      DATASET_API_URL: ''
      DATASET_AUTH_TOKEN: ''
      DOWNLOAD_SERVICE_TOKEN: ''
      FILTER_API_URL: ''
      IMAGE_API_URL: ''
      SERVICE_AUTH_TOKEN: ''
      SECRET_KEY: ''
      ZEBEDEE_URL: ''
      IS_PUBLISHING: ''
      PUBLIC_BUCKET_URL: 'https://csv-exported.s3.eu-west-2.amazonaws.com/'
    volumes:
      - ./:/service

  localstack:
    image: localstack/localstack
    ports:
      - '4566-4583:4566-4583'
    environment:
      - SERVICES=s3
      - DEBUG=0
      - AWS_DEFAULT_REGION=eu-west-2
      - EDGE_PORT=4566
    volumes:
      - ./aws:/docker-entrypoint-initaws.d
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
