// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service_test

import (
	"context"
	auth "github.com/ONSdigital/dp-authorisation/v2/authorisation"
	"github.com/ONSdigital/dp-download-service/config"
	"github.com/ONSdigital/dp-download-service/content"
	"github.com/ONSdigital/dp-download-service/downloads"
	"github.com/ONSdigital/dp-download-service/service"
	"net/http"
	"sync"
)

// Ensure, that DependenciesMock does implement service.Dependencies.
// If this is not the case, regenerate this file with moq.
var _ service.Dependencies = &DependenciesMock{}

// DependenciesMock is a mock implementation of service.Dependencies.
//
//	func TestSomethingThatUsesDependencies(t *testing.T) {
//
//		// make and configure a mocked service.Dependencies
//		mockedDependencies := &DependenciesMock{
//			AuthMiddlewareFunc: func(contextMoqParam context.Context, configMoqParam *config.Config) (auth.Middleware, error) {
//				panic("mock out the AuthMiddleware method")
//			},
//			DatasetClientFunc: func(s string) downloads.DatasetClient {
//				panic("mock out the DatasetClient method")
//			},
//			FilesClientFunc: func(s string) downloads.FilesClient {
//				panic("mock out the FilesClient method")
//			},
//			FilterClientFunc: func(s string) downloads.FilterClient {
//				panic("mock out the FilterClient method")
//			},
//			HealthCheckFunc: func(configMoqParam *config.Config, s1 string, s2 string, s3 string) (service.HealthChecker, error) {
//				panic("mock out the HealthCheck method")
//			},
//			HttpServerFunc: func(configMoqParam *config.Config, handler http.Handler) service.HTTPServer {
//				panic("mock out the HttpServer method")
//			},
//			ImageClientFunc: func(s string) downloads.ImageClient {
//				panic("mock out the ImageClient method")
//			},
//			S3ClientFunc: func(contextMoqParam context.Context, configMoqParam *config.Config) (content.S3Client, error) {
//				panic("mock out the S3Client method")
//			},
//		}
//
//		// use mockedDependencies in code that requires service.Dependencies
//		// and then make assertions.
//
//	}
type DependenciesMock struct {
	// AuthMiddlewareFunc mocks the AuthMiddleware method.
	AuthMiddlewareFunc func(contextMoqParam context.Context, configMoqParam *config.Config) (auth.Middleware, error)

	// DatasetClientFunc mocks the DatasetClient method.
	DatasetClientFunc func(s string) downloads.DatasetClient

	// FilesClientFunc mocks the FilesClient method.
	FilesClientFunc func(s string) downloads.FilesClient

	// FilterClientFunc mocks the FilterClient method.
	FilterClientFunc func(s string) downloads.FilterClient

	// HealthCheckFunc mocks the HealthCheck method.
	HealthCheckFunc func(configMoqParam *config.Config, s1 string, s2 string, s3 string) (service.HealthChecker, error)

	// HttpServerFunc mocks the HttpServer method.
	HttpServerFunc func(configMoqParam *config.Config, handler http.Handler) service.HTTPServer

	// ImageClientFunc mocks the ImageClient method.
	ImageClientFunc func(s string) downloads.ImageClient

	// S3ClientFunc mocks the S3Client method.
	S3ClientFunc func(contextMoqParam context.Context, configMoqParam *config.Config) (content.S3Client, error)

	// calls tracks calls to the methods.
	calls struct {
		// AuthMiddleware holds details about calls to the AuthMiddleware method.
		AuthMiddleware []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// ConfigMoqParam is the configMoqParam argument value.
			ConfigMoqParam *config.Config
		}
		// DatasetClient holds details about calls to the DatasetClient method.
		DatasetClient []struct {
			// S is the s argument value.
			S string
		}
		// FilesClient holds details about calls to the FilesClient method.
		FilesClient []struct {
			// S is the s argument value.
			S string
		}
		// FilterClient holds details about calls to the FilterClient method.
		FilterClient []struct {
			// S is the s argument value.
			S string
		}
		// HealthCheck holds details about calls to the HealthCheck method.
		HealthCheck []struct {
			// ConfigMoqParam is the configMoqParam argument value.
			ConfigMoqParam *config.Config
			// S1 is the s1 argument value.
			S1 string
			// S2 is the s2 argument value.
			S2 string
			// S3 is the s3 argument value.
			S3 string
		}
		// HttpServer holds details about calls to the HttpServer method.
		HttpServer []struct {
			// ConfigMoqParam is the configMoqParam argument value.
			ConfigMoqParam *config.Config
			// Handler is the handler argument value.
			Handler http.Handler
		}
		// ImageClient holds details about calls to the ImageClient method.
		ImageClient []struct {
			// S is the s argument value.
			S string
		}
		// S3Client holds details about calls to the S3Client method.
		S3Client []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// ConfigMoqParam is the configMoqParam argument value.
			ConfigMoqParam *config.Config
		}
	}
	lockAuthMiddleware sync.RWMutex
	lockDatasetClient  sync.RWMutex
	lockFilesClient    sync.RWMutex
	lockFilterClient   sync.RWMutex
	lockHealthCheck    sync.RWMutex
	lockHttpServer     sync.RWMutex
	lockImageClient    sync.RWMutex
	lockS3Client       sync.RWMutex
}

// AuthMiddleware calls AuthMiddlewareFunc.
func (mock *DependenciesMock) AuthMiddleware(contextMoqParam context.Context, configMoqParam *config.Config) (auth.Middleware, error) {
	if mock.AuthMiddlewareFunc == nil {
		panic("DependenciesMock.AuthMiddlewareFunc: method is nil but Dependencies.AuthMiddleware was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		ConfigMoqParam  *config.Config
	}{
		ContextMoqParam: contextMoqParam,
		ConfigMoqParam:  configMoqParam,
	}
	mock.lockAuthMiddleware.Lock()
	mock.calls.AuthMiddleware = append(mock.calls.AuthMiddleware, callInfo)
	mock.lockAuthMiddleware.Unlock()
	return mock.AuthMiddlewareFunc(contextMoqParam, configMoqParam)
}

// AuthMiddlewareCalls gets all the calls that were made to AuthMiddleware.
// Check the length with:
//
//	len(mockedDependencies.AuthMiddlewareCalls())
func (mock *DependenciesMock) AuthMiddlewareCalls() []struct {
	ContextMoqParam context.Context
	ConfigMoqParam  *config.Config
} {
	var calls []struct {
		ContextMoqParam context.Context
		ConfigMoqParam  *config.Config
	}
	mock.lockAuthMiddleware.RLock()
	calls = mock.calls.AuthMiddleware
	mock.lockAuthMiddleware.RUnlock()
	return calls
}

// DatasetClient calls DatasetClientFunc.
func (mock *DependenciesMock) DatasetClient(s string) downloads.DatasetClient {
	if mock.DatasetClientFunc == nil {
		panic("DependenciesMock.DatasetClientFunc: method is nil but Dependencies.DatasetClient was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockDatasetClient.Lock()
	mock.calls.DatasetClient = append(mock.calls.DatasetClient, callInfo)
	mock.lockDatasetClient.Unlock()
	return mock.DatasetClientFunc(s)
}

// DatasetClientCalls gets all the calls that were made to DatasetClient.
// Check the length with:
//
//	len(mockedDependencies.DatasetClientCalls())
func (mock *DependenciesMock) DatasetClientCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockDatasetClient.RLock()
	calls = mock.calls.DatasetClient
	mock.lockDatasetClient.RUnlock()
	return calls
}

// FilesClient calls FilesClientFunc.
func (mock *DependenciesMock) FilesClient(s string) downloads.FilesClient {
	if mock.FilesClientFunc == nil {
		panic("DependenciesMock.FilesClientFunc: method is nil but Dependencies.FilesClient was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockFilesClient.Lock()
	mock.calls.FilesClient = append(mock.calls.FilesClient, callInfo)
	mock.lockFilesClient.Unlock()
	return mock.FilesClientFunc(s)
}

// FilesClientCalls gets all the calls that were made to FilesClient.
// Check the length with:
//
//	len(mockedDependencies.FilesClientCalls())
func (mock *DependenciesMock) FilesClientCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockFilesClient.RLock()
	calls = mock.calls.FilesClient
	mock.lockFilesClient.RUnlock()
	return calls
}

// FilterClient calls FilterClientFunc.
func (mock *DependenciesMock) FilterClient(s string) downloads.FilterClient {
	if mock.FilterClientFunc == nil {
		panic("DependenciesMock.FilterClientFunc: method is nil but Dependencies.FilterClient was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockFilterClient.Lock()
	mock.calls.FilterClient = append(mock.calls.FilterClient, callInfo)
	mock.lockFilterClient.Unlock()
	return mock.FilterClientFunc(s)
}

// FilterClientCalls gets all the calls that were made to FilterClient.
// Check the length with:
//
//	len(mockedDependencies.FilterClientCalls())
func (mock *DependenciesMock) FilterClientCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockFilterClient.RLock()
	calls = mock.calls.FilterClient
	mock.lockFilterClient.RUnlock()
	return calls
}

// HealthCheck calls HealthCheckFunc.
func (mock *DependenciesMock) HealthCheck(configMoqParam *config.Config, s1 string, s2 string, s3 string) (service.HealthChecker, error) {
	if mock.HealthCheckFunc == nil {
		panic("DependenciesMock.HealthCheckFunc: method is nil but Dependencies.HealthCheck was just called")
	}
	callInfo := struct {
		ConfigMoqParam *config.Config
		S1             string
		S2             string
		S3             string
	}{
		ConfigMoqParam: configMoqParam,
		S1:             s1,
		S2:             s2,
		S3:             s3,
	}
	mock.lockHealthCheck.Lock()
	mock.calls.HealthCheck = append(mock.calls.HealthCheck, callInfo)
	mock.lockHealthCheck.Unlock()
	return mock.HealthCheckFunc(configMoqParam, s1, s2, s3)
}

// HealthCheckCalls gets all the calls that were made to HealthCheck.
// Check the length with:
//
//	len(mockedDependencies.HealthCheckCalls())
func (mock *DependenciesMock) HealthCheckCalls() []struct {
	ConfigMoqParam *config.Config
	S1             string
	S2             string
	S3             string
} {
	var calls []struct {
		ConfigMoqParam *config.Config
		S1             string
		S2             string
		S3             string
	}
	mock.lockHealthCheck.RLock()
	calls = mock.calls.HealthCheck
	mock.lockHealthCheck.RUnlock()
	return calls
}

// HttpServer calls HttpServerFunc.
func (mock *DependenciesMock) HttpServer(configMoqParam *config.Config, handler http.Handler) service.HTTPServer {
	if mock.HttpServerFunc == nil {
		panic("DependenciesMock.HttpServerFunc: method is nil but Dependencies.HttpServer was just called")
	}
	callInfo := struct {
		ConfigMoqParam *config.Config
		Handler        http.Handler
	}{
		ConfigMoqParam: configMoqParam,
		Handler:        handler,
	}
	mock.lockHttpServer.Lock()
	mock.calls.HttpServer = append(mock.calls.HttpServer, callInfo)
	mock.lockHttpServer.Unlock()
	return mock.HttpServerFunc(configMoqParam, handler)
}

// HttpServerCalls gets all the calls that were made to HttpServer.
// Check the length with:
//
//	len(mockedDependencies.HttpServerCalls())
func (mock *DependenciesMock) HttpServerCalls() []struct {
	ConfigMoqParam *config.Config
	Handler        http.Handler
} {
	var calls []struct {
		ConfigMoqParam *config.Config
		Handler        http.Handler
	}
	mock.lockHttpServer.RLock()
	calls = mock.calls.HttpServer
	mock.lockHttpServer.RUnlock()
	return calls
}

// ImageClient calls ImageClientFunc.
func (mock *DependenciesMock) ImageClient(s string) downloads.ImageClient {
	if mock.ImageClientFunc == nil {
		panic("DependenciesMock.ImageClientFunc: method is nil but Dependencies.ImageClient was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockImageClient.Lock()
	mock.calls.ImageClient = append(mock.calls.ImageClient, callInfo)
	mock.lockImageClient.Unlock()
	return mock.ImageClientFunc(s)
}

// ImageClientCalls gets all the calls that were made to ImageClient.
// Check the length with:
//
//	len(mockedDependencies.ImageClientCalls())
func (mock *DependenciesMock) ImageClientCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockImageClient.RLock()
	calls = mock.calls.ImageClient
	mock.lockImageClient.RUnlock()
	return calls
}

// S3Client calls S3ClientFunc.
func (mock *DependenciesMock) S3Client(contextMoqParam context.Context, configMoqParam *config.Config) (content.S3Client, error) {
	if mock.S3ClientFunc == nil {
		panic("DependenciesMock.S3ClientFunc: method is nil but Dependencies.S3Client was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		ConfigMoqParam  *config.Config
	}{
		ContextMoqParam: contextMoqParam,
		ConfigMoqParam:  configMoqParam,
	}
	mock.lockS3Client.Lock()
	mock.calls.S3Client = append(mock.calls.S3Client, callInfo)
	mock.lockS3Client.Unlock()
	return mock.S3ClientFunc(contextMoqParam, configMoqParam)
}

// S3ClientCalls gets all the calls that were made to S3Client.
// Check the length with:
//
//	len(mockedDependencies.S3ClientCalls())
func (mock *DependenciesMock) S3ClientCalls() []struct {
	ContextMoqParam context.Context
	ConfigMoqParam  *config.Config
} {
	var calls []struct {
		ContextMoqParam context.Context
		ConfigMoqParam  *config.Config
	}
	mock.lockS3Client.RLock()
	calls = mock.calls.S3Client
	mock.lockS3Client.RUnlock()
	return calls
}
