// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service_test

import (
	"context"
	"github.com/ONSdigital/dp-api-clients-go/v2/dataset"
	"github.com/ONSdigital/dp-api-clients-go/v2/filter"
	"github.com/ONSdigital/dp-api-clients-go/v2/identity"
	"github.com/ONSdigital/dp-api-clients-go/v2/image"
	"github.com/ONSdigital/dp-download-service/downloads"
	filesAPIModels "github.com/ONSdigital/dp-files-api/files"
	filesAPISDK "github.com/ONSdigital/dp-files-api/sdk"
	"github.com/ONSdigital/dp-healthcheck/healthcheck"
	dprequest "github.com/ONSdigital/dp-net/v3/request"
	"sync"
)

// Ensure, that DatasetClientMock does implement downloads.DatasetClient.
// If this is not the case, regenerate this file with moq.
var _ downloads.DatasetClient = &DatasetClientMock{}

// DatasetClientMock is a mock implementation of downloads.DatasetClient.
//
//	func TestSomethingThatUsesDatasetClient(t *testing.T) {
//
//		// make and configure a mocked downloads.DatasetClient
//		mockedDatasetClient := &DatasetClientMock{
//			CheckerFunc: func(ctx context.Context, check *healthcheck.CheckState) error {
//				panic("mock out the Checker method")
//			},
//			GetInstanceFunc: func(ctx context.Context, userAuthToken string, serviceAuthToken string, collectionID string, instanceID string, ifMatch string) (dataset.Instance, string, error) {
//				panic("mock out the GetInstance method")
//			},
//			GetVersionFunc: func(ctx context.Context, userAuthToken string, serviceAuthToken string, downloadServiceAuthToken string, collectionID string, datasetID string, edition string, version string) (dataset.Version, error) {
//				panic("mock out the GetVersion method")
//			},
//		}
//
//		// use mockedDatasetClient in code that requires downloads.DatasetClient
//		// and then make assertions.
//
//	}
type DatasetClientMock struct {
	// CheckerFunc mocks the Checker method.
	CheckerFunc func(ctx context.Context, check *healthcheck.CheckState) error

	// GetInstanceFunc mocks the GetInstance method.
	GetInstanceFunc func(ctx context.Context, userAuthToken string, serviceAuthToken string, collectionID string, instanceID string, ifMatch string) (dataset.Instance, string, error)

	// GetVersionFunc mocks the GetVersion method.
	GetVersionFunc func(ctx context.Context, userAuthToken string, serviceAuthToken string, downloadServiceAuthToken string, collectionID string, datasetID string, edition string, version string) (dataset.Version, error)

	// calls tracks calls to the methods.
	calls struct {
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Check is the check argument value.
			Check *healthcheck.CheckState
		}
		// GetInstance holds details about calls to the GetInstance method.
		GetInstance []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserAuthToken is the userAuthToken argument value.
			UserAuthToken string
			// ServiceAuthToken is the serviceAuthToken argument value.
			ServiceAuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// InstanceID is the instanceID argument value.
			InstanceID string
			// IfMatch is the ifMatch argument value.
			IfMatch string
		}
		// GetVersion holds details about calls to the GetVersion method.
		GetVersion []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserAuthToken is the userAuthToken argument value.
			UserAuthToken string
			// ServiceAuthToken is the serviceAuthToken argument value.
			ServiceAuthToken string
			// DownloadServiceAuthToken is the downloadServiceAuthToken argument value.
			DownloadServiceAuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// DatasetID is the datasetID argument value.
			DatasetID string
			// Edition is the edition argument value.
			Edition string
			// Version is the version argument value.
			Version string
		}
	}
	lockChecker     sync.RWMutex
	lockGetInstance sync.RWMutex
	lockGetVersion  sync.RWMutex
}

// Checker calls CheckerFunc.
func (mock *DatasetClientMock) Checker(ctx context.Context, check *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("DatasetClientMock.CheckerFunc: method is nil but DatasetClient.Checker was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Check *healthcheck.CheckState
	}{
		Ctx:   ctx,
		Check: check,
	}
	mock.lockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	mock.lockChecker.Unlock()
	return mock.CheckerFunc(ctx, check)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//
//	len(mockedDatasetClient.CheckerCalls())
func (mock *DatasetClientMock) CheckerCalls() []struct {
	Ctx   context.Context
	Check *healthcheck.CheckState
} {
	var calls []struct {
		Ctx   context.Context
		Check *healthcheck.CheckState
	}
	mock.lockChecker.RLock()
	calls = mock.calls.Checker
	mock.lockChecker.RUnlock()
	return calls
}

// GetInstance calls GetInstanceFunc.
func (mock *DatasetClientMock) GetInstance(ctx context.Context, userAuthToken string, serviceAuthToken string, collectionID string, instanceID string, ifMatch string) (dataset.Instance, string, error) {
	if mock.GetInstanceFunc == nil {
		panic("DatasetClientMock.GetInstanceFunc: method is nil but DatasetClient.GetInstance was just called")
	}
	callInfo := struct {
		Ctx              context.Context
		UserAuthToken    string
		ServiceAuthToken string
		CollectionID     string
		InstanceID       string
		IfMatch          string
	}{
		Ctx:              ctx,
		UserAuthToken:    userAuthToken,
		ServiceAuthToken: serviceAuthToken,
		CollectionID:     collectionID,
		InstanceID:       instanceID,
		IfMatch:          ifMatch,
	}
	mock.lockGetInstance.Lock()
	mock.calls.GetInstance = append(mock.calls.GetInstance, callInfo)
	mock.lockGetInstance.Unlock()
	return mock.GetInstanceFunc(ctx, userAuthToken, serviceAuthToken, collectionID, instanceID, ifMatch)
}

// GetInstanceCalls gets all the calls that were made to GetInstance.
// Check the length with:
//
//	len(mockedDatasetClient.GetInstanceCalls())
func (mock *DatasetClientMock) GetInstanceCalls() []struct {
	Ctx              context.Context
	UserAuthToken    string
	ServiceAuthToken string
	CollectionID     string
	InstanceID       string
	IfMatch          string
} {
	var calls []struct {
		Ctx              context.Context
		UserAuthToken    string
		ServiceAuthToken string
		CollectionID     string
		InstanceID       string
		IfMatch          string
	}
	mock.lockGetInstance.RLock()
	calls = mock.calls.GetInstance
	mock.lockGetInstance.RUnlock()
	return calls
}

// GetVersion calls GetVersionFunc.
func (mock *DatasetClientMock) GetVersion(ctx context.Context, userAuthToken string, serviceAuthToken string, downloadServiceAuthToken string, collectionID string, datasetID string, edition string, version string) (dataset.Version, error) {
	if mock.GetVersionFunc == nil {
		panic("DatasetClientMock.GetVersionFunc: method is nil but DatasetClient.GetVersion was just called")
	}
	callInfo := struct {
		Ctx                      context.Context
		UserAuthToken            string
		ServiceAuthToken         string
		DownloadServiceAuthToken string
		CollectionID             string
		DatasetID                string
		Edition                  string
		Version                  string
	}{
		Ctx:                      ctx,
		UserAuthToken:            userAuthToken,
		ServiceAuthToken:         serviceAuthToken,
		DownloadServiceAuthToken: downloadServiceAuthToken,
		CollectionID:             collectionID,
		DatasetID:                datasetID,
		Edition:                  edition,
		Version:                  version,
	}
	mock.lockGetVersion.Lock()
	mock.calls.GetVersion = append(mock.calls.GetVersion, callInfo)
	mock.lockGetVersion.Unlock()
	return mock.GetVersionFunc(ctx, userAuthToken, serviceAuthToken, downloadServiceAuthToken, collectionID, datasetID, edition, version)
}

// GetVersionCalls gets all the calls that were made to GetVersion.
// Check the length with:
//
//	len(mockedDatasetClient.GetVersionCalls())
func (mock *DatasetClientMock) GetVersionCalls() []struct {
	Ctx                      context.Context
	UserAuthToken            string
	ServiceAuthToken         string
	DownloadServiceAuthToken string
	CollectionID             string
	DatasetID                string
	Edition                  string
	Version                  string
} {
	var calls []struct {
		Ctx                      context.Context
		UserAuthToken            string
		ServiceAuthToken         string
		DownloadServiceAuthToken string
		CollectionID             string
		DatasetID                string
		Edition                  string
		Version                  string
	}
	mock.lockGetVersion.RLock()
	calls = mock.calls.GetVersion
	mock.lockGetVersion.RUnlock()
	return calls
}

// Ensure, that FilesClientMock does implement downloads.FilesClient.
// If this is not the case, regenerate this file with moq.
var _ downloads.FilesClient = &FilesClientMock{}

// FilesClientMock is a mock implementation of downloads.FilesClient.
//
//	func TestSomethingThatUsesFilesClient(t *testing.T) {
//
//		// make and configure a mocked downloads.FilesClient
//		mockedFilesClient := &FilesClientMock{
//			CheckerFunc: func(ctx context.Context, state *healthcheck.CheckState) error {
//				panic("mock out the Checker method")
//			},
//			CreateFileEventFunc: func(ctx context.Context, event filesAPIModels.FileEvent, headers filesAPISDK.Headers) (*filesAPIModels.FileEvent, error) {
//				panic("mock out the CreateFileEvent method")
//			},
//			GetFileFunc: func(ctx context.Context, filePath string, headers filesAPISDK.Headers) (*filesAPIModels.StoredRegisteredMetaData, error) {
//				panic("mock out the GetFile method")
//			},
//		}
//
//		// use mockedFilesClient in code that requires downloads.FilesClient
//		// and then make assertions.
//
//	}
type FilesClientMock struct {
	// CheckerFunc mocks the Checker method.
	CheckerFunc func(ctx context.Context, state *healthcheck.CheckState) error

	// CreateFileEventFunc mocks the CreateFileEvent method.
	CreateFileEventFunc func(ctx context.Context, event filesAPIModels.FileEvent, headers filesAPISDK.Headers) (*filesAPIModels.FileEvent, error)

	// GetFileFunc mocks the GetFile method.
	GetFileFunc func(ctx context.Context, filePath string, headers filesAPISDK.Headers) (*filesAPIModels.StoredRegisteredMetaData, error)

	// calls tracks calls to the methods.
	calls struct {
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// State is the state argument value.
			State *healthcheck.CheckState
		}
		// CreateFileEvent holds details about calls to the CreateFileEvent method.
		CreateFileEvent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Event is the event argument value.
			Event filesAPIModels.FileEvent
			// Headers is the headers argument value.
			Headers filesAPISDK.Headers
		}
		// GetFile holds details about calls to the GetFile method.
		GetFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FilePath is the filePath argument value.
			FilePath string
			// Headers is the headers argument value.
			Headers filesAPISDK.Headers
		}
	}
	lockChecker         sync.RWMutex
	lockCreateFileEvent sync.RWMutex
	lockGetFile         sync.RWMutex
}

// Checker calls CheckerFunc.
func (mock *FilesClientMock) Checker(ctx context.Context, state *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("FilesClientMock.CheckerFunc: method is nil but FilesClient.Checker was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}{
		Ctx:   ctx,
		State: state,
	}
	mock.lockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	mock.lockChecker.Unlock()
	return mock.CheckerFunc(ctx, state)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//
//	len(mockedFilesClient.CheckerCalls())
func (mock *FilesClientMock) CheckerCalls() []struct {
	Ctx   context.Context
	State *healthcheck.CheckState
} {
	var calls []struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}
	mock.lockChecker.RLock()
	calls = mock.calls.Checker
	mock.lockChecker.RUnlock()
	return calls
}

// CreateFileEvent calls CreateFileEventFunc.
func (mock *FilesClientMock) CreateFileEvent(ctx context.Context, event filesAPIModels.FileEvent, headers filesAPISDK.Headers) (*filesAPIModels.FileEvent, error) {
	if mock.CreateFileEventFunc == nil {
		panic("FilesClientMock.CreateFileEventFunc: method is nil but FilesClient.CreateFileEvent was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Event   filesAPIModels.FileEvent
		Headers filesAPISDK.Headers
	}{
		Ctx:     ctx,
		Event:   event,
		Headers: headers,
	}
	mock.lockCreateFileEvent.Lock()
	mock.calls.CreateFileEvent = append(mock.calls.CreateFileEvent, callInfo)
	mock.lockCreateFileEvent.Unlock()
	return mock.CreateFileEventFunc(ctx, event, headers)
}

// CreateFileEventCalls gets all the calls that were made to CreateFileEvent.
// Check the length with:
//
//	len(mockedFilesClient.CreateFileEventCalls())
func (mock *FilesClientMock) CreateFileEventCalls() []struct {
	Ctx     context.Context
	Event   filesAPIModels.FileEvent
	Headers filesAPISDK.Headers
} {
	var calls []struct {
		Ctx     context.Context
		Event   filesAPIModels.FileEvent
		Headers filesAPISDK.Headers
	}
	mock.lockCreateFileEvent.RLock()
	calls = mock.calls.CreateFileEvent
	mock.lockCreateFileEvent.RUnlock()
	return calls
}

// GetFile calls GetFileFunc.
func (mock *FilesClientMock) GetFile(ctx context.Context, filePath string, headers filesAPISDK.Headers) (*filesAPIModels.StoredRegisteredMetaData, error) {
	if mock.GetFileFunc == nil {
		panic("FilesClientMock.GetFileFunc: method is nil but FilesClient.GetFile was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		FilePath string
		Headers  filesAPISDK.Headers
	}{
		Ctx:      ctx,
		FilePath: filePath,
		Headers:  headers,
	}
	mock.lockGetFile.Lock()
	mock.calls.GetFile = append(mock.calls.GetFile, callInfo)
	mock.lockGetFile.Unlock()
	return mock.GetFileFunc(ctx, filePath, headers)
}

// GetFileCalls gets all the calls that were made to GetFile.
// Check the length with:
//
//	len(mockedFilesClient.GetFileCalls())
func (mock *FilesClientMock) GetFileCalls() []struct {
	Ctx      context.Context
	FilePath string
	Headers  filesAPISDK.Headers
} {
	var calls []struct {
		Ctx      context.Context
		FilePath string
		Headers  filesAPISDK.Headers
	}
	mock.lockGetFile.RLock()
	calls = mock.calls.GetFile
	mock.lockGetFile.RUnlock()
	return calls
}

// Ensure, that FilterClientMock does implement downloads.FilterClient.
// If this is not the case, regenerate this file with moq.
var _ downloads.FilterClient = &FilterClientMock{}

// FilterClientMock is a mock implementation of downloads.FilterClient.
//
//	func TestSomethingThatUsesFilterClient(t *testing.T) {
//
//		// make and configure a mocked downloads.FilterClient
//		mockedFilterClient := &FilterClientMock{
//			CheckerFunc: func(ctx context.Context, check *healthcheck.CheckState) error {
//				panic("mock out the Checker method")
//			},
//			GetOutputFunc: func(ctx context.Context, userAuthToken string, serviceAuthToken string, downloadServiceToken string, collectionID string, filterOutputID string) (filter.Model, error) {
//				panic("mock out the GetOutput method")
//			},
//		}
//
//		// use mockedFilterClient in code that requires downloads.FilterClient
//		// and then make assertions.
//
//	}
type FilterClientMock struct {
	// CheckerFunc mocks the Checker method.
	CheckerFunc func(ctx context.Context, check *healthcheck.CheckState) error

	// GetOutputFunc mocks the GetOutput method.
	GetOutputFunc func(ctx context.Context, userAuthToken string, serviceAuthToken string, downloadServiceToken string, collectionID string, filterOutputID string) (filter.Model, error)

	// calls tracks calls to the methods.
	calls struct {
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Check is the check argument value.
			Check *healthcheck.CheckState
		}
		// GetOutput holds details about calls to the GetOutput method.
		GetOutput []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserAuthToken is the userAuthToken argument value.
			UserAuthToken string
			// ServiceAuthToken is the serviceAuthToken argument value.
			ServiceAuthToken string
			// DownloadServiceToken is the downloadServiceToken argument value.
			DownloadServiceToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// FilterOutputID is the filterOutputID argument value.
			FilterOutputID string
		}
	}
	lockChecker   sync.RWMutex
	lockGetOutput sync.RWMutex
}

// Checker calls CheckerFunc.
func (mock *FilterClientMock) Checker(ctx context.Context, check *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("FilterClientMock.CheckerFunc: method is nil but FilterClient.Checker was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Check *healthcheck.CheckState
	}{
		Ctx:   ctx,
		Check: check,
	}
	mock.lockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	mock.lockChecker.Unlock()
	return mock.CheckerFunc(ctx, check)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//
//	len(mockedFilterClient.CheckerCalls())
func (mock *FilterClientMock) CheckerCalls() []struct {
	Ctx   context.Context
	Check *healthcheck.CheckState
} {
	var calls []struct {
		Ctx   context.Context
		Check *healthcheck.CheckState
	}
	mock.lockChecker.RLock()
	calls = mock.calls.Checker
	mock.lockChecker.RUnlock()
	return calls
}

// GetOutput calls GetOutputFunc.
func (mock *FilterClientMock) GetOutput(ctx context.Context, userAuthToken string, serviceAuthToken string, downloadServiceToken string, collectionID string, filterOutputID string) (filter.Model, error) {
	if mock.GetOutputFunc == nil {
		panic("FilterClientMock.GetOutputFunc: method is nil but FilterClient.GetOutput was just called")
	}
	callInfo := struct {
		Ctx                  context.Context
		UserAuthToken        string
		ServiceAuthToken     string
		DownloadServiceToken string
		CollectionID         string
		FilterOutputID       string
	}{
		Ctx:                  ctx,
		UserAuthToken:        userAuthToken,
		ServiceAuthToken:     serviceAuthToken,
		DownloadServiceToken: downloadServiceToken,
		CollectionID:         collectionID,
		FilterOutputID:       filterOutputID,
	}
	mock.lockGetOutput.Lock()
	mock.calls.GetOutput = append(mock.calls.GetOutput, callInfo)
	mock.lockGetOutput.Unlock()
	return mock.GetOutputFunc(ctx, userAuthToken, serviceAuthToken, downloadServiceToken, collectionID, filterOutputID)
}

// GetOutputCalls gets all the calls that were made to GetOutput.
// Check the length with:
//
//	len(mockedFilterClient.GetOutputCalls())
func (mock *FilterClientMock) GetOutputCalls() []struct {
	Ctx                  context.Context
	UserAuthToken        string
	ServiceAuthToken     string
	DownloadServiceToken string
	CollectionID         string
	FilterOutputID       string
} {
	var calls []struct {
		Ctx                  context.Context
		UserAuthToken        string
		ServiceAuthToken     string
		DownloadServiceToken string
		CollectionID         string
		FilterOutputID       string
	}
	mock.lockGetOutput.RLock()
	calls = mock.calls.GetOutput
	mock.lockGetOutput.RUnlock()
	return calls
}

// Ensure, that IdentityClientMock does implement downloads.IdentityClient.
// If this is not the case, regenerate this file with moq.
var _ downloads.IdentityClient = &IdentityClientMock{}

// IdentityClientMock is a mock implementation of downloads.IdentityClient.
//
//	func TestSomethingThatUsesIdentityClient(t *testing.T) {
//
//		// make and configure a mocked downloads.IdentityClient
//		mockedIdentityClient := &IdentityClientMock{
//			CheckTokenIdentityFunc: func(ctx context.Context, token string, tokenType identity.TokenType) (*dprequest.IdentityResponse, error) {
//				panic("mock out the CheckTokenIdentity method")
//			},
//		}
//
//		// use mockedIdentityClient in code that requires downloads.IdentityClient
//		// and then make assertions.
//
//	}
type IdentityClientMock struct {
	// CheckTokenIdentityFunc mocks the CheckTokenIdentity method.
	CheckTokenIdentityFunc func(ctx context.Context, token string, tokenType identity.TokenType) (*dprequest.IdentityResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// CheckTokenIdentity holds details about calls to the CheckTokenIdentity method.
		CheckTokenIdentity []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
			// TokenType is the tokenType argument value.
			TokenType identity.TokenType
		}
	}
	lockCheckTokenIdentity sync.RWMutex
}

// CheckTokenIdentity calls CheckTokenIdentityFunc.
func (mock *IdentityClientMock) CheckTokenIdentity(ctx context.Context, token string, tokenType identity.TokenType) (*dprequest.IdentityResponse, error) {
	if mock.CheckTokenIdentityFunc == nil {
		panic("IdentityClientMock.CheckTokenIdentityFunc: method is nil but IdentityClient.CheckTokenIdentity was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Token     string
		TokenType identity.TokenType
	}{
		Ctx:       ctx,
		Token:     token,
		TokenType: tokenType,
	}
	mock.lockCheckTokenIdentity.Lock()
	mock.calls.CheckTokenIdentity = append(mock.calls.CheckTokenIdentity, callInfo)
	mock.lockCheckTokenIdentity.Unlock()
	return mock.CheckTokenIdentityFunc(ctx, token, tokenType)
}

// CheckTokenIdentityCalls gets all the calls that were made to CheckTokenIdentity.
// Check the length with:
//
//	len(mockedIdentityClient.CheckTokenIdentityCalls())
func (mock *IdentityClientMock) CheckTokenIdentityCalls() []struct {
	Ctx       context.Context
	Token     string
	TokenType identity.TokenType
} {
	var calls []struct {
		Ctx       context.Context
		Token     string
		TokenType identity.TokenType
	}
	mock.lockCheckTokenIdentity.RLock()
	calls = mock.calls.CheckTokenIdentity
	mock.lockCheckTokenIdentity.RUnlock()
	return calls
}

// Ensure, that ImageClientMock does implement downloads.ImageClient.
// If this is not the case, regenerate this file with moq.
var _ downloads.ImageClient = &ImageClientMock{}

// ImageClientMock is a mock implementation of downloads.ImageClient.
//
//	func TestSomethingThatUsesImageClient(t *testing.T) {
//
//		// make and configure a mocked downloads.ImageClient
//		mockedImageClient := &ImageClientMock{
//			CheckerFunc: func(ctx context.Context, check *healthcheck.CheckState) error {
//				panic("mock out the Checker method")
//			},
//			GetDownloadVariantFunc: func(ctx context.Context, userAuthToken string, serviceAuthToken string, collectionID string, imageID string, variant string) (image.ImageDownload, error) {
//				panic("mock out the GetDownloadVariant method")
//			},
//		}
//
//		// use mockedImageClient in code that requires downloads.ImageClient
//		// and then make assertions.
//
//	}
type ImageClientMock struct {
	// CheckerFunc mocks the Checker method.
	CheckerFunc func(ctx context.Context, check *healthcheck.CheckState) error

	// GetDownloadVariantFunc mocks the GetDownloadVariant method.
	GetDownloadVariantFunc func(ctx context.Context, userAuthToken string, serviceAuthToken string, collectionID string, imageID string, variant string) (image.ImageDownload, error)

	// calls tracks calls to the methods.
	calls struct {
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Check is the check argument value.
			Check *healthcheck.CheckState
		}
		// GetDownloadVariant holds details about calls to the GetDownloadVariant method.
		GetDownloadVariant []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserAuthToken is the userAuthToken argument value.
			UserAuthToken string
			// ServiceAuthToken is the serviceAuthToken argument value.
			ServiceAuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// ImageID is the imageID argument value.
			ImageID string
			// Variant is the variant argument value.
			Variant string
		}
	}
	lockChecker            sync.RWMutex
	lockGetDownloadVariant sync.RWMutex
}

// Checker calls CheckerFunc.
func (mock *ImageClientMock) Checker(ctx context.Context, check *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("ImageClientMock.CheckerFunc: method is nil but ImageClient.Checker was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Check *healthcheck.CheckState
	}{
		Ctx:   ctx,
		Check: check,
	}
	mock.lockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	mock.lockChecker.Unlock()
	return mock.CheckerFunc(ctx, check)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//
//	len(mockedImageClient.CheckerCalls())
func (mock *ImageClientMock) CheckerCalls() []struct {
	Ctx   context.Context
	Check *healthcheck.CheckState
} {
	var calls []struct {
		Ctx   context.Context
		Check *healthcheck.CheckState
	}
	mock.lockChecker.RLock()
	calls = mock.calls.Checker
	mock.lockChecker.RUnlock()
	return calls
}

// GetDownloadVariant calls GetDownloadVariantFunc.
func (mock *ImageClientMock) GetDownloadVariant(ctx context.Context, userAuthToken string, serviceAuthToken string, collectionID string, imageID string, variant string) (image.ImageDownload, error) {
	if mock.GetDownloadVariantFunc == nil {
		panic("ImageClientMock.GetDownloadVariantFunc: method is nil but ImageClient.GetDownloadVariant was just called")
	}
	callInfo := struct {
		Ctx              context.Context
		UserAuthToken    string
		ServiceAuthToken string
		CollectionID     string
		ImageID          string
		Variant          string
	}{
		Ctx:              ctx,
		UserAuthToken:    userAuthToken,
		ServiceAuthToken: serviceAuthToken,
		CollectionID:     collectionID,
		ImageID:          imageID,
		Variant:          variant,
	}
	mock.lockGetDownloadVariant.Lock()
	mock.calls.GetDownloadVariant = append(mock.calls.GetDownloadVariant, callInfo)
	mock.lockGetDownloadVariant.Unlock()
	return mock.GetDownloadVariantFunc(ctx, userAuthToken, serviceAuthToken, collectionID, imageID, variant)
}

// GetDownloadVariantCalls gets all the calls that were made to GetDownloadVariant.
// Check the length with:
//
//	len(mockedImageClient.GetDownloadVariantCalls())
func (mock *ImageClientMock) GetDownloadVariantCalls() []struct {
	Ctx              context.Context
	UserAuthToken    string
	ServiceAuthToken string
	CollectionID     string
	ImageID          string
	Variant          string
} {
	var calls []struct {
		Ctx              context.Context
		UserAuthToken    string
		ServiceAuthToken string
		CollectionID     string
		ImageID          string
		Variant          string
	}
	mock.lockGetDownloadVariant.RLock()
	calls = mock.calls.GetDownloadVariant
	mock.lockGetDownloadVariant.RUnlock()
	return calls
}
