// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ONSdigital/dp-download-service/handlers (interfaces: DatasetDownloads,S3Content)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	downloads "github.com/ONSdigital/dp-download-service/downloads"
	gomock "github.com/golang/mock/gomock"
	io "io"
	reflect "reflect"
)

// MockDatasetDownloads is a mock of DatasetDownloads interface
type MockDatasetDownloads struct {
	ctrl     *gomock.Controller
	recorder *MockDatasetDownloadsMockRecorder
}

// MockDatasetDownloadsMockRecorder is the mock recorder for MockDatasetDownloads
type MockDatasetDownloadsMockRecorder struct {
	mock *MockDatasetDownloads
}

// NewMockDatasetDownloads creates a new mock instance
func NewMockDatasetDownloads(ctrl *gomock.Controller) *MockDatasetDownloads {
	mock := &MockDatasetDownloads{ctrl: ctrl}
	mock.recorder = &MockDatasetDownloadsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDatasetDownloads) EXPECT() *MockDatasetDownloadsMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockDatasetDownloads) Get(arg0 context.Context, arg1 downloads.Parameters) (downloads.Model, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(downloads.Model)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockDatasetDownloadsMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDatasetDownloads)(nil).Get), arg0, arg1)
}

// MockS3Content is a mock of S3Content interface
type MockS3Content struct {
	ctrl     *gomock.Controller
	recorder *MockS3ContentMockRecorder
}

// MockS3ContentMockRecorder is the mock recorder for MockS3Content
type MockS3ContentMockRecorder struct {
	mock *MockS3Content
}

// NewMockS3Content creates a new mock instance
func NewMockS3Content(ctrl *gomock.Controller) *MockS3Content {
	mock := &MockS3Content{ctrl: ctrl}
	mock.recorder = &MockS3ContentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockS3Content) EXPECT() *MockS3ContentMockRecorder {
	return m.recorder
}

// StreamAndWrite mocks base method
func (m *MockS3Content) StreamAndWrite(arg0 context.Context, arg1 string, arg2 io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamAndWrite", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamAndWrite indicates an expected call of StreamAndWrite
func (mr *MockS3ContentMockRecorder) StreamAndWrite(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamAndWrite", reflect.TypeOf((*MockS3Content)(nil).StreamAndWrite), arg0, arg1, arg2)
}
