---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.24.9-bookworm

inputs:
  - name: dp-download-service
    path: dp-download-service

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-download-service/ci/scripts/build.sh
