---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tags: 1.10.0

inputs:
  - name: dp-download-service
    path: go/src/github.com/ONSdigital/dp-download-service

outputs:
  - name: build

run:
  path: go/src/github.com/ONSdigital/dp-download-service/ci/scripts/build.sh
