---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.12.12

inputs:
  - name: dp-download-service
    path: dp-download-service

outputs:
  - name: build

run:
  path: dp-download-service/ci/scripts/build.sh
